# Automatically generated by Pynguin.
import script_43 as module_0


def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.pairs_sum_to_zero(set_0)
    assert var_0 is False
    assert module_0.METADATA == {}


def test_case_1():
    bytes_0 = b"@\xa8'\xb7l\xca`"
    var_0 = module_0.pairs_sum_to_zero(bytes_0)
    assert var_0 is False
    assert module_0.METADATA == {}


def test_case_2():
    bytes_0 = b'r\x9d\x01\xe7\x14\x04A7\xd5&\x8c\xf0\xba\x9b\x87'
    var_0 = module_0.pairs_sum_to_zero(bytes_0)
    assert var_0 is False
    assert module_0.METADATA == {}
    bool_0 = False
    list_0 = [var_0, bool_0]
    var_1 = module_0.pairs_sum_to_zero(list_0)
    assert var_1 is True
    float_0 = 1827.72961
    str_0 = '(##)2NY5>NLw\t2J8'
    var_2 = module_0.pairs_sum_to_zero(str_0)
    assert var_2 is False
    tuple_0 = float_0,
    var_3 = module_0.pairs_sum_to_zero(tuple_0)
    assert var_3 is False
    var_4 = module_0.pairs_sum_to_zero(bytes_0)
    assert var_4 is False
