# Automatically generated by Pynguin.
import script_130 as module_0


def test_case_0():
    try:
        str_0 = None
        bool_0 = False
        var_0 = module_0.tri(bool_0)
        assert var_0 == [1]
        var_1 = module_0.tri(str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.tri(set_0)
    except BaseException:
        pass


def test_case_2():
    try:
        str_0 = '`)}~(x[ACuc6O'
        int_0 = 2899
        var_0 = module_0.tri(int_0)
        assert len(var_0) == 2900
        var_1 = module_0.tri(str_0)
    except BaseException:
        pass


def test_case_3():
    try:
        int_0 = -2191
        var_0 = module_0.tri(int_0)
        assert var_0 == [1, 3]
        float_0 = None
        var_1 = module_0.tri(float_0)
    except BaseException:
        pass
