# Automatically generated by Pynguin.
import script_46 as module_0


def test_case_0():
    int_0 = 214
    var_0 = module_0.fib4(int_0)
    assert var_0 == 1439508847912177806794441527953940981237469767608360515526842
    assert module_0.METADATA == {}
