# Automatically generated by Pynguin.
import script_131 as module_0


def test_case_0():
    try:
        int_0 = 2899
        var_0 = module_0.digits(int_0)
        assert var_0 == 81
        int_1 = -842
        var_1 = module_0.digits(int_1)
    except BaseException:
        pass


def test_case_1():
    try:
        float_0 = 1957.138153
        var_0 = module_0.digits(float_0)
    except BaseException:
        pass
