# Automatically generated by Pynguin.
import script_122 as module_0


def test_case_0():
    tuple_0 = ()
    bytes_0 = None
    var_0 = module_0.add_elements(tuple_0, bytes_0)



def test_case_1():
    tuple_0 = ()
    none_type_0 = None
    var_0 = module_0.add_elements(tuple_0, none_type_0)
    assert var_0 == 0
    


def test_case_3():
    float_0 = -196.5
    list_0 = [float_0, float_0]
    set_0 = set()
    tuple_0 = (list_0, set_0, float_0, float_0)
    none_type_0 = None
    var_0 = module_0.add_elements(tuple_0, none_type_0)
    assert var_0 == 0
    