# Automatically generated by Pynguin.
import script_122 as module_0


def test_case_0():
    try:
        str_0 = '11d( H{aphZ\r+UkDGZj'
        bool_0 = None
        var_0 = module_0.add_elements(str_0, bool_0)
    except BaseException:
        pass


def test_case_1():
    try:
        int_0 = None
        list_0 = [int_0, int_0, int_0, int_0]
        set_0 = None
        var_0 = module_0.add_elements(list_0, set_0)
        assert var_0 == 0
        bytes_0 = None
        dict_0 = {}
        var_1 = module_0.add_elements(bytes_0, dict_0)
    except BaseException:
        pass
