# Automatically generated by Pynguin.

import script_92 as module_0

def test_case_0():
    int_0 = -2973
    int_1 = 815
    bool_0 = module_0.any_int(int_0, int_0, int_1)
    assert bool_0 is False
