# Automatically generated by Pynguin.
import script_30 as module_0


def test_case_0():
    try:
        int_0 = -897
        list_0 = [int_0, int_0]
        var_0 = module_0.get_positive(list_0)
        assert var_0 == []
        var_1 = module_0.get_positive(list_0)
        assert var_1 == []
        bool_0 = False
        var_2 = module_0.get_positive(list_0)
        assert var_2 == []
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_3 = module_0.get_positive(list_0)
        assert var_3 == []
        var_4 = module_0.get_positive(list_0)
        assert var_4 == []
        list_1 = [set_0, bool_0, set_0]
        var_5 = module_0.get_positive(list_1)
    except BaseException:
        pass
