# Automatically generated by Pynguin.
import pytest
import script_66 as module_0


def test_case_2():
    str_0 = "\rQl"
    var_0 = module_0.digitSum(str_0)
    assert var_0 == 81
    


def test_case_3():
    str_0 = ""
    var_0 = module_0.digitSum(str_0)
    assert var_0 == 0
    var_1 = module_0.digitSum(str_0)
    assert var_1 == 0
    list_0 = []
    var_2 = module_0.digitSum(list_0)
    assert var_2 == 0
    var_3 = module_0.digitSum(list_0)
    assert var_3 == 0
   