# Automatically generated by Pynguin.
import script_10 as module_0


def test_case_0():
    try:
        str_0 = 'pc3ql>BaYeDOY!['
        str_1 = module_0.make_palindrome(str_0)
        assert str_1 == 'pc3ql>BaYeDOY![!YODeYaB>lq3cp'
        assert module_0.METADATA == {'author': 'jt', 'dataset': 'test'}
        str_2 = None
        bool_0 = module_0.is_palindrome(str_2)
    except BaseException:
        pass
