# Automatically generated by Pynguin.
import script_104 as module_0


def test_case_0():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.unique_digits(set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.unique_digits(bytes_0)
        assert var_0 == [39]
    except BaseException:
        pass
