# Automatically generated by Pynguin.
import script_57 as module_0


def test_case_0():
    try:
        list_0 = []
        var_0 = module_0.monotonic(list_0)
        assert var_0 is True
        list_1 = [list_0, list_0, list_0]
        list_2 = [list_0, list_0, list_1, list_0]
        var_1 = module_0.monotonic(list_2)
        assert var_1 is False
        str_0 = 'Ua/5T F:w3bt],.'
        str_1 = 'bYIQGF\\dkGQ_"A['
        set_0 = None
        dict_0 = {str_0: str_0, str_1: set_0, str_1: str_1, str_0: set_0}
        list_3 = [str_0, dict_0]
        var_2 = module_0.monotonic(list_3)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = False
        list_0 = [bool_0]
        var_0 = module_0.monotonic(list_0)
        assert var_0 is True
        list_1 = [var_0, bool_0]
        var_1 = module_0.monotonic(list_1)
        assert var_1 is True
        var_2 = module_0.monotonic(list_1)
        assert var_2 is True
        var_3 = module_0.monotonic(list_0)
        assert var_3 is True
        var_4 = module_0.monotonic(list_1)
        assert var_4 is True
        var_5 = module_0.monotonic(list_0)
        assert var_5 is True
        list_2 = None
        var_6 = module_0.monotonic(list_2)
    except BaseException:
        pass
