# Automatically generated by Pynguin.
import script_126 as module_0


def test_case_0():
    try:
        int_0 = 2516
        list_0 = [int_0, int_0, int_0, int_0]
        var_0 = module_0.is_sorted(list_0)
        assert var_0 is False
        dict_0 = {int_0: int_0, int_0: int_0, int_0: int_0, int_0: int_0}
        bytes_0 = b'\\\x1b\x17\x01\xf1Nq\\\xc2E'
        var_1 = module_0.is_sorted(bytes_0)
        assert var_1 is False
        tuple_0 = dict_0,
        var_2 = module_0.is_sorted(tuple_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.is_sorted(bytes_0)
        assert var_0 is False
    except BaseException:
        pass
