# Automatically generated by Pynguin.
import script_107 as module_0


def test_case_0():
    try:
        str_0 = '`)}~(x[ACuc6O'
        int_0 = 2899
        var_0 = module_0.even_odd_palindrome(int_0)
        assert var_0 == (57, 70)
        var_1 = module_0.even_odd_palindrome(str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        int_0 = -2191
        var_0 = module_0.even_odd_palindrome(int_0)
        assert var_0 == (0, 0)
        float_0 = None
        var_1 = module_0.even_odd_palindrome(float_0)
    except BaseException:
        pass


def test_case_2():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.even_odd_palindrome(set_0)
    except BaseException:
        pass
