# Automatically generated by Pynguin.
import script_108 as module_0


def test_case_0():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.count_nums(set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        int_0 = -1222
        str_0 = 'z1kJ##qI{&N$8m'
        set_0 = {int_0, str_0, str_0}
        var_0 = module_0.count_nums(set_0)
    except BaseException:
        pass
