# Automatically generated by Pynguin.
import script_157 as module_0


def test_case_0():
    bool_0 = False
    float_0 = -249.04553252677673
    var_0 = module_0.right_angle_triangle(bool_0, float_0, bool_0)
    assert var_0 is False
