# Automatically generated by Pynguin.
import script_157 as module_0


def test_case_0():
    try:
        float_0 = -533.814
        tuple_0 = ()
        str_0 = 'x4d/TI~ET:$eN,ow5{'
        var_0 = module_0.right_angle_triangle(float_0, tuple_0, str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        float_0 = -533.814
        bool_0 = False
        int_0 = -373
        var_0 = module_0.right_angle_triangle(bool_0, int_0, int_0)
        assert var_0 is True
        float_1 = 62023.67727154581
        bytes_0 = b'\xc5JL\xd2'
        var_1 = module_0.right_angle_triangle(float_0, float_1, bytes_0)
    except BaseException:
        pass


def test_case_2():
    try:
        bool_0 = False
        complex_0 = None
        int_0 = -3739
        var_0 = module_0.right_angle_triangle(int_0, int_0, bool_0)
        assert var_0 is True
        float_0 = -602.40666
        float_1 = 1803.89371
        float_2 = 1462.4859
        set_0 = {int_0, float_1, float_2, var_0}
        tuple_0 = float_1, float_2, set_0
        dict_0 = None
        bytes_0 = b'v\x06\xbf\xe4\x12Y \xed\x9eY\r\xc1\xcfj>\xc1\xdc'
        tuple_1 = tuple_0, dict_0, bytes_0
        var_1 = module_0.right_angle_triangle(complex_0, float_0, tuple_1)
    except BaseException:
        pass
