# Automatically generated by Pynguin.
import script_115 as module_0


def test_case_0():
    try:
        bytes_0 = b"G'7\xf5\xc3V\x1a\x17a\x18"
        str_0 = '~'
        var_0 = module_0.max_fill(bytes_0, str_0)
    except BaseException:
        pass
