# Automatically generated by Pynguin.
import script_115 as module_0


def test_case_0():
    tuple_0 = ()
    bytes_0 = None
    var_0 = module_0.max_fill(tuple_0, bytes_0)


def test_case_1():
    list_0 = []
    var_0 = module_0.max_fill(list_0, list_0)
    assert var_0 == 0
    