# Automatically generated by Pynguin.
import script_28 as module_0


def test_case_0():
    list_0 = []
    str_0 = module_0.concatenate(list_0)
    assert module_0.METADATA == {'author': 'jt', 'dataset': 'test'}
    str_1 = module_0.concatenate(list_0)
