# Automatically generated by Pynguin.

import script_148 as module_0


def test_case_0():
    str_0 = "n"
    var_0 = module_0.bf(str_0, str_0)


def test_case_1():
    str_0 = "Mars"
    var_0 = module_0.bf(str_0, str_0)


