# Automatically generated by Pynguin.
import pytest
import script_47 as module_0


def test_case_0():
    float_0 = 890.6
    list_0 = [float_0, float_0, float_0, float_0]
    var_0 = module_0.median(list_0)
    assert var_0 == pytest.approx(890.6, abs=0.01, rel=0.01)

