# Automatically generated by Pynguin.
import script_47 as module_0


def test_case_0():
    try:
        str_0 = '_*s^F\x0b\x0c7t4EPy8r+|Er@'
        list_0 = [str_0]
        var_0 = module_0.median(list_0)
        assert var_0 == '_*s^F\x0b\x0c7t4EPy8r+|Er@'
        assert module_0.METADATA == {}
        list_1 = []
        var_1 = module_0.median(list_1)
    except BaseException:
        pass
