# Automatically generated by Pynguin.
import script_137 as module_0


def test_case_0():
    try:
        bytes_0 = b"G'7\xf5\xc3V\x1a\x17a\x18"
        str_0 = '~'
        var_0 = module_0.compare_one(bytes_0, str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.compare_one(tuple_0, bytes_0)
    except BaseException:
        pass


def test_case_2():
    try:
        bool_0 = True
        int_0 = -643
        var_0 = module_0.compare_one(bool_0, int_0)
        assert var_0 is True
        bool_1 = False
        tuple_0 = None
        var_1 = module_0.compare_one(bool_1, tuple_0)
    except BaseException:
        pass


def test_case_3():
    try:
        float_0 = 1205.170231
        str_0 = '<\tjukmQ3m GQ\\'
        bool_0 = False
        int_0 = 78
        var_0 = module_0.compare_one(bool_0, int_0)
        assert var_0 == 78
        var_1 = module_0.compare_one(str_0, float_0)
    except BaseException:
        pass


def test_case_4():
    try:
        bool_0 = False
        bool_1 = False
        var_0 = module_0.compare_one(bool_0, bool_1)
        assert var_0 is None
        set_0 = set()
        var_1 = module_0.compare_one(set_0, bool_0)
    except BaseException:
        pass
