# Automatically generated by Pynguin.
import script_117 as module_0


def test_case_0():
    str_0 = "k|'Anm{_\\jkue5E,gUx"
    str_1 = '\\'
    var_0 = module_0.select_words(str_0, str_1)
    assert var_0 == []
