# Automatically generated by Pynguin.

import script_99 as module_0



def test_case_3():
    str_0 = "5"
    var_0 = module_0.closest_integer(str_0)
    assert var_0 == 5


def test_case_4():
    str_0 = ".5"
    var_0 = module_0.closest_integer(str_0)
    assert var_0 == 1


def test_case_5():
    str_0 = ".50"
    var_0 = module_0.closest_integer(str_0)
    assert var_0 == 1



def test_case_6():
    str_0 = "-.5"
    var_0 = module_0.closest_integer(str_0)
    assert var_0 == -1
    
