# Automatically generated by Pynguin.
import script_40 as module_0


def test_case_0():
    float_0 = 890.6
    list_0 = [float_0, float_0, float_0, float_0]
    var_0 = module_0.triples_sum_to_zero(list_0)
    assert var_0 is False
