# Automatically generated by Pynguin.
import script_18 as module_0


def test_case_0():
    str_0 = ''
    int_0 = module_0.how_many_times(str_0, str_0)
    assert int_0 == 1
    assert module_0.METADATA == {'author': 'jt', 'dataset': 'test'}


def test_case_1():
    str_0 = '41C+:dGAW'
    str_1 = '#Xyo'
    int_0 = module_0.how_many_times(str_0, str_1)
    assert int_0 == 0
    assert module_0.METADATA == {'author': 'jt', 'dataset': 'test'}
