# Automatically generated by Pynguin.
import script_18 as module_0


def test_case_0():
    try:
        str_0 = None
        int_0 = module_0.how_many_times(str_0, str_0)
    except BaseException:
        pass
