# Automatically generated by Pynguin.
import pytest
import script_114 as module_0


def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.minSubArraySum(set_0)
    assert var_0 == 0


def test_case_1():
    bool_0 = True
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.minSubArraySum(set_0)
    assert var_0 == 1


def test_case_2():
    float_0 = -2471.0
    list_0 = [float_0, float_0, float_0]
    var_0 = module_0.minSubArraySum(list_0)
    assert var_0 == pytest.approx(-7413.0, abs=0.01, rel=0.01)
    bool_0 = False
    list_1 = [bool_0]
    var_1 = module_0.minSubArraySum(list_1)
    assert var_1 == 0
