# Automatically generated by Pynguin.
import script_5 as module_0


def test_case_0():
    int_0 = -4215
    list_0 = [int_0]
    int_1 = 2005
    list_1 = module_0.intersperse(list_0, int_1)
    assert list_1 == [-4215]



def test_case_1():
    list_0 = None
    int_0 = None
    list_1 = module_0.intersperse(list_0, int_0)
    assert list_1 == []

    int_1 = -594
    list_2 = module_0.intersperse(list_1, int_1)
    assert list_2 == []
    int_2 = -106
    list_3 = module_0.intersperse(list_0, int_2)
    assert list_3 == []


def test_case_2():
    int_0 = -2251
    int_1 = 790
    list_0 = [int_0, int_0, int_1, int_0]
    int_2 = -4027
    list_1 = module_0.intersperse(list_0, int_2)
    assert list_1 == [-2251, -4027, -2251, -4027, 790, -4027, -2251]

