# Automatically generated by Pynguin.
import script_101 as module_0


def test_case_0():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.words_string(set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        int_0 = -2266
        int_1 = None
        var_0 = module_0.words_string(int_1)
        assert var_0 == []
        set_0 = None
        var_1 = module_0.words_string(set_0)
        assert var_1 == []
        var_2 = module_0.words_string(int_0)
    except BaseException:
        pass


def test_case_2():
    try:
        str_0 = "t)7N%R'^Y,uYCaO|4#"
        var_0 = module_0.words_string(str_0)
        assert var_0 == ["t)7N%R'^Y", 'uYCaO|4#']
        bool_0 = False
        set_0 = {bool_0}
        var_1 = module_0.words_string(set_0)
    except BaseException:
        pass
