# Automatically generated by Pynguin.
import script_134 as module_0


def test_case_0():
    str_0 = ';7d,~='
    var_0 = module_0.check_if_last_char_is_a_letter(str_0)
    assert var_0 is False
    str_1 = '='
    var_1 = module_0.check_if_last_char_is_a_letter(str_1)
    assert var_1 is False


def test_case_1():
    str_0 = 'X'
    var_0 = module_0.check_if_last_char_is_a_letter(str_0)
    assert var_0 is True


def test_case_2():
    str_0 = 'p'
    var_0 = module_0.check_if_last_char_is_a_letter(str_0)
    assert var_0 is True
    var_1 = module_0.check_if_last_char_is_a_letter(str_0)
    assert var_1 is True
    str_1 = '|'
    var_2 = module_0.check_if_last_char_is_a_letter(str_1)
    assert var_2 is False
