# Automatically generated by Pynguin.
import q4 as module_0


def test_case_0():
    try:
        str_0 = '!n&4Hai'
        var_0 = module_0.sort_age(str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = 'MLnV5xUXxsy'
        list_0 = [str_0, str_0]
        str_1 = 'M&K`p5'
        bool_0 = None
        tuple_0 = str_1, list_0, bool_0
        var_0 = module_0.sort_age(tuple_0)
    except BaseException:
        pass
