# Automatically generated by Pynguin.
import q4 as module_0


def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.sort_age(set_0)


def test_case_1():
    str_0 = 'MLnV5xUXxsy'
    list_0 = [str_0, str_0]
    var_0 = module_0.sort_age(list_0)
