# Automatically generated by Pynguin.
import script_118 as module_0


def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.get_closest_vowel(set_0)
    assert var_0 == ''


def test_case_1():
    str_0 = "t)7N%R'^Y,uYCaO|4#"
    var_0 = module_0.get_closest_vowel(str_0)
    assert var_0 == 'u'
    str_1 = 'MLnV5xUXxsy'
    list_0 = [str_1, str_1]
    bool_0 = False
    set_0 = {bool_0}
    var_1 = module_0.get_closest_vowel(set_0)
    assert var_1 == ''
    var_2 = module_0.get_closest_vowel(list_0)
    assert var_2 == ''
