# Automatically generated by Pynguin.
import script_127 as module_0


def test_case_0():
    bytes_0 = b"jmBW-QA\xb7d\x1d\x0eJ\xfa"
    var_0 = module_0.intersection(bytes_0, bytes_0)
    assert var_0 == "YES"


def test_case_4():
    bytes_0 = b"jlW-Qk\xf5\x1d\x0e\t"
    var_0 = module_0.intersection(bytes_0, bytes_0)
    assert var_0 == "YES"
