# Automatically generated by Pynguin.
import script_119 as module_0


def test_case_0():
    str_0 = 'VXh0y\rz827{'
    var_0 = module_0.match_parens(str_0)
    assert var_0 == 'No'


def test_case_1():
    str_0 = "Q(/7]y\rc!h'i0"
    var_0 = module_0.match_parens(str_0)
    assert var_0 == 'Yes'


def test_case_2():
    str_0 = 'MLnV5xUXxsy'
    list_0 = [str_0, str_0]
    str_1 = '{p$'
    var_0 = module_0.match_parens(str_1)
    assert var_0 == 'No'
    str_2 = '(?g0'
    var_1 = module_0.match_parens(str_2)
    assert var_1 == 'Yes'
    var_2 = module_0.match_parens(list_0)
    assert var_2 == 'No'
    var_3 = module_0.match_parens(list_0)
    assert var_3 == 'No'
