# Automatically generated by Pynguin.
import script_119 as module_0


def test_case_0():
    try:
        str_0 = 'MLnV5xUXxsy'
        list_0 = [str_0, str_0]
        str_1 = "((/7]y\rc!h'i0"
        var_0 = module_0.match_parens(str_1)
        assert var_0 == 'No'
        str_2 = '?kw^/uPue'
        var_1 = module_0.match_parens(str_2)
        assert var_1 == 'No'
        var_2 = module_0.match_parens(list_0)
        assert var_2 == 'No'
        bool_0 = True
        var_3 = module_0.match_parens(bool_0)
    except BaseException:
        pass
