# Automatically generated by Pynguin.
import script_48 as module_0


def test_case_0():
    str_0 = 'dN#.'
    var_0 = module_0.is_palindrome(str_0)
    assert var_0 is False



def test_case_1():
    str_0 = 'B'
    str_1 = ';Z{3T@l:Tk6cGqoQ`)}'
    var_0 = module_0.is_palindrome(str_1)
    assert var_0 is False

    var_1 = module_0.is_palindrome(str_0)
    assert var_1 is True
    str_2 = ',)!j6K0SbB[='
    var_2 = module_0.is_palindrome(str_2)
    assert var_2 is False
    var_3 = module_0.is_palindrome(str_0)
    assert var_3 is True
