# Automatically generated by Pynguin.
import script_154 as module_0


def test_case_0():
    str_0 = "n"
    var_0 = module_0.cycpattern_check(str_0, str_0)
    assert var_0 is True
    var_1 = module_0.cycpattern_check(str_0, str_0)
    assert var_1 is True



def test_case_1():
    bytes_0 = b'\xd9\xbc$\xb4\xd9"4\x1eP\xfc!=\x9aT\xd6'
    none_type_0 = None
    list_0 = [none_type_0]
    var_0 = module_0.cycpattern_check(bytes_0, list_0)
    assert var_0 is False
   