# Automatically generated by Pynguin.
import script_154 as module_0


def test_case_0():
    try:
        bool_0 = True
        int_0 = -643
        bytes_0 = b"G'7\xf5\xc3V\x1a\x17a\x18"
        str_0 = '~'
        var_0 = module_0.cycpattern_check(bytes_0, str_0)
        assert var_0 is False
        var_1 = module_0.cycpattern_check(bool_0, int_0)
    except BaseException:
        pass


def test_case_1():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.cycpattern_check(tuple_0, bytes_0)
    except BaseException:
        pass


def test_case_2():
    try:
        str_0 = '-itX>wWw\\1XA](k'
        var_0 = module_0.cycpattern_check(str_0, str_0)
        assert var_0 is True
        float_0 = 1997.34
        bytes_0 = None
        var_1 = module_0.cycpattern_check(float_0, bytes_0)
    except BaseException:
        pass
