# Automatically generated by Pynguin.
import script_39 as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.prime_fib(bool_0)
    assert var_0 == 2



def test_case_1():
    bool_0 = True
    var_0 = module_0.prime_fib(bool_0)
    assert var_0 == 2
    var_1 = module_0.prime_fib(var_0)
    assert var_1 == 3
    var_2 = module_0.prime_fib(var_1)
    assert var_2 == 5
    bool_1 = False
    var_3 = module_0.prime_fib(bool_1)
    assert var_3 == 1
    var_4 = module_0.prime_fib(var_2)
    assert var_4 == 89
    var_5 = module_0.prime_fib(var_0)
    assert var_5 == 3
