# Automatically generated by Pynguin.
import script_52 as module_0


def test_case_0():
    try:
        bytes_0 = None
        list_0 = [bytes_0, bytes_0, bytes_0, bytes_0]
        int_0 = 2842
        var_0 = module_0.below_threshold(list_0, int_0)
    except BaseException:
        pass
