# Automatically generated by Pynguin.
import script_163 as module_0


def test_case_0():
    try:
        bool_0 = True
        float_0 = 1205.170231
        var_0 = module_0.generate_integers(bool_0, float_0)
        assert var_0 == [2, 4, 6, 8]
        str_0 = '<\tjukmQ3m GQ\\'
        var_1 = module_0.generate_integers(str_0, bool_0)
    except BaseException:
        pass


def test_case_1():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.generate_integers(tuple_0, bytes_0)
    except BaseException:
        pass
