# Automatically generated by Pynguin.
import script_158 as module_0


def test_case_0():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.find_max(set_0)
    except BaseException:
        pass
