# Automatically generated by Pynguin.
import script_70 as module_0


def test_case_0():
    try:
        int_0 = 2516
        list_0 = [int_0, int_0, int_0, int_0]
        var_0 = module_0.strange_sort_list(list_0)
        assert var_0 == [2516, 2516, 2516, 2516]
        bytes_0 = b'\\\x1b\x17\x01\xf1Nq\\\xc2E'
        var_1 = module_0.strange_sort_list(bytes_0)
    except BaseException:
        pass
