# Automatically generated by Pynguin.
import script_87 as module_0


def test_case_0():
    try:
        bytes_0 = b"G'7\xf5\xc3V\x1a\x17a\x18"
        str_0 = '~'
        var_0 = module_0.get_row(bytes_0, str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = "k|'Anm{_\\jkue5E,gUx"
        str_1 = '\\'
        var_0 = module_0.get_row(str_0, str_1)
        assert var_0 == [(8, 0)]
        bool_0 = True
        dict_0 = {}
        var_1 = module_0.get_row(bool_0, dict_0)
    except BaseException:
        pass


def test_case_2():
    try:
        str_0 = '~bLHnePP'
        list_0 = [str_0, str_0, str_0]
        bytes_0 = b'\x1c\xe3ip\x0b\x10B\xa7P\x03\xb4\xde\xad\x86\xc4'
        var_0 = module_0.get_row(list_0, bytes_0)
        assert var_0 == []
    except BaseException:
        pass
