# Automatically generated by Pynguin.
import script_12 as module_0


def test_case_0():
    str_0 = 'AzK?6J`9bF`\ngucO[k\x0b7'
    list_0 = [str_0]
    var_0 = module_0.longest(list_0)
    assert var_0 == 'AzK?6J`9bF`\ngucO[k\x0b7'



def test_case_1():
    list_0 = []
    var_0 = module_0.longest(list_0)
    assert var_0 is None

    var_1 = module_0.longest(list_0)
    assert var_1 is None
    var_2 = module_0.longest(list_0)
    assert var_2 is None
    var_3 = module_0.longest(list_0)
    assert var_3 is None
    var_4 = module_0.longest(list_0)
    assert var_4 is None


def test_case_2():
    str_0 = 'a W'
    str_1 = '|B_.H&^H(KZP\r7cC'
    str_2 = '\x0b$"-wi7]-Fl6\n'
    list_0 = [str_0, str_1, str_2]
    var_0 = module_0.longest(list_0)
    assert var_0 == '|B_.H&^H(KZP\r7cC'

    str_3 = 'zMk@>fn0:Oi\x0c+kol3'
    list_1 = [str_0, str_3]
    var_1 = module_0.longest(list_1)
    assert var_1 == 'zMk@>fn0:Oi\x0c+kol3'
    list_2 = [str_0, str_0, str_0]
    var_2 = module_0.longest(list_2)
    assert var_2 == 'a W'
