# Automatically generated by Pynguin.
import script_90 as module_0


def test_case_0():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.next_smallest(bytes_0)
        assert var_0 == 64
    except BaseException:
        pass
