# Automatically generated by Pynguin.
import pytest
import script_2 as module_0


def test_case_0():
    float_0 = -3824.1715
    float_1 = module_0.truncate_number(float_0)
    assert float_1 == pytest.approx(0.8285000000000764, abs=0.01, rel=0.01)

