# Automatically generated by Pynguin.
import script_156 as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.int_to_mini_roman(bool_0)
    assert var_0 == "i"


def test_case_1():
    none_type_0 = None
    var_0 = module_0.int_to_mini_roman(none_type_0)
    assert var_0 == ""
    var_1 = module_0.int_to_mini_roman(var_0)
    assert var_1 == ""