# Automatically generated by Pynguin.
import script_68 as module_0


def test_case_0():
    try:
        set_0 = set()
        var_0 = module_0.pluck(set_0)
        tuple_0 = None
        var_1 = module_0.pluck(tuple_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.pluck(set_0)
    except BaseException:
        pass
