# Automatically generated by Pynguin.
import script_68 as module_0


def test_case_0():
    bool_0 = True
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.pluck(set_0)
    assert var_0 == []
