# Automatically generated by Pynguin.
import script_109 as module_0


def test_case_0():
    try:
        tuple_0 = ()
        list_0 = [tuple_0]
        var_0 = module_0.move_one_ball(list_0)
        assert var_0 is True
        var_1 = module_0.move_one_ball(tuple_0)
        assert var_1 is True
        bool_0 = True
        var_2 = module_0.move_one_ball(bool_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.move_one_ball(set_0)
    except BaseException:
        pass


def test_case_2():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.move_one_ball(bytes_0)
        assert var_0 is False
    except BaseException:
        pass
