# Automatically generated by Pynguin.
import script_109 as module_0


def test_case_0():
    set_0 = set()
    bytes_0 = b'\x9a\xb7\xd1\x1e\xa9:j\xcfT\xb8\x1d'
    tuple_0 = bytes_0,
    var_0 = module_0.move_one_ball(tuple_0)
    assert var_0 is True
    tuple_1 = set_0, set_0
    var_1 = module_0.move_one_ball(tuple_1)
    assert var_1 is True
