# Automatically generated by Pynguin.
import script_135 as module_0


def test_case_0():
    try:
        dict_0 = {}
        list_0 = [dict_0, dict_0]
        var_0 = module_0.can_arrange(list_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.can_arrange(bytes_0)
        assert var_0 == 6
    except BaseException:
        pass
