# Automatically generated by Pynguin.
import pytest
import script_4 as module_0


def test_case_0():
    float_0 = 3537.268441
    list_0 = [float_0]
    float_1 = module_0.mean_absolute_deviation(list_0)
    assert float_1 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert module_0.METADATA == {'author': 'jt', 'dataset': 'test'}
    float_2 = module_0.mean_absolute_deviation(list_0)
    assert float_2 == pytest.approx(0.0, abs=0.01, rel=0.01)
