# Automatically generated by Pynguin.
import script_7 as module_0


def test_case_0():
    str_0 = '4 '
    list_0 = [str_0, str_0, str_0, str_0]
    list_1 = module_0.filter_by_substring(list_0, str_0)
    assert list_1 == ['4 ', '4 ', '4 ', '4 ']



def test_case_1():
    str_0 = 'vFT-s.j'
    str_1 = '5'
    str_2 = '&OZ`cV"ua*\n1_'
    list_0 = [str_0, str_1, str_2]
    str_3 = 'u?b2Z\\Dk{'
    list_1 = module_0.filter_by_substring(list_0, str_3)
    assert list_1 == []

