# Automatically generated by Pynguin.
import script_146 as module_0


def test_case_0():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.specialFilter(bytes_0)
        assert var_0 == 2
    except BaseException:
        pass
