# Automatically generated by Pynguin.
import script_146 as module_0


def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.specialFilter(set_0)
    assert var_0 == 0
