# Automatically generated by Pynguin.
import script_103 as module_0


def test_case_0():
    try:
        str_0 = 'Qn\x0bh\x0b?~?R'
        str_1 = "Ma^[(h@Ifm'O"
        var_0 = module_0.rounded_avg(str_0, str_1)
        assert var_0 == -1
        bytes_0 = (
            b'_j\xb3\x8c\xe9x\xc1\x89\xcd\xaa\xd37\xc3?\xae\xc1\x98\xdf\xc9')
        str_2 = "9+e7)#p,'jl"
        var_1 = module_0.rounded_avg(bytes_0, str_2)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = True
        float_0 = 1205.170231
        var_0 = module_0.rounded_avg(bool_0, float_0)
    except BaseException:
        pass


def test_case_2():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.rounded_avg(tuple_0, bytes_0)
    except BaseException:
        pass


def test_case_3():
    try:
        bool_0 = False
        int_0 = 2257
        var_0 = module_0.rounded_avg(bool_0, int_0)
        assert var_0 == '0b10001101000'
        tuple_0 = None
        var_1 = module_0.rounded_avg(bool_0, tuple_0)
    except BaseException:
        pass
