# Automatically generated by Pynguin.
import script_103 as module_0


def test_case_0():
    list_0 = []
    float_0 = 966.3564
    tuple_0 = (list_0, list_0, float_0)
    list_1 = [tuple_0]
    var_0 = module_0.rounded_avg(list_1, list_0)
    assert var_0 == -1
   


def test_case_2():
    int_0 = 63
    none_type_0 = None
    var_0 = module_0.rounded_avg(int_0, int_0)
    assert var_0 == "0b111111"
    