# Automatically generated by Pynguin.
import script_113 as module_0


def test_case_0():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.odd_count(set_0)
    except BaseException:
        pass
