# Automatically generated by Pynguin.
import script_113 as module_0


def test_case_0():
    dict_0 = {}
    list_0 = [dict_0, dict_0]
    var_0 = module_0.odd_count(list_0)
    assert var_0 == ['the number of odd elements 0n the str0ng 0 of the 0nput.'
        , 'the number of odd elements 0n the str0ng 0 of the 0nput.']
    tuple_0 = ()
    var_1 = module_0.odd_count(tuple_0)
    assert var_1 == []


def test_case_1():
    set_0 = set()
    bytes_0 = b'\x9a\xb7\xd1\x1e\xa9:j\xcfT\xb8\x1d'
    tuple_0 = bytes_0,
    var_0 = module_0.odd_count(tuple_0)
    assert var_0 == ['the number of odd elements 5n the str5ng 5 of the 5nput.'
        ]
    tuple_1 = set_0, set_0
    var_1 = module_0.odd_count(tuple_1)
    assert var_1 == ['the number of odd elements 0n the str0ng 0 of the 0nput.'
        , 'the number of odd elements 0n the str0ng 0 of the 0nput.']
