# Automatically generated by Pynguin.
import script_110 as module_0


def test_case_0():
    try:
        list_0 = []
        var_0 = module_0.exchange(list_0, list_0)
        assert var_0 == 'YES'
        bool_0 = False
        str_0 = 'I~?iudiwpm:'
        var_1 = module_0.exchange(bool_0, str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        int_0 = 1855
        bytes_0 = (
            b'\r\xc6\xee\xa0\x9d\xd7\xa9M}\xca\x92\x8c[\x12\xc8\xb5Q\x868')
        bytes_1 = b'j\x8b\x89g\x17'
        var_0 = module_0.exchange(bytes_0, bytes_1)
        assert var_0 == 'NO'
        float_0 = None
        var_1 = module_0.exchange(int_0, float_0)
    except BaseException:
        pass


def test_case_2():
    try:
        bytes_0 = b"G'7\xf5\xc3V\x1a\x17a\x18"
        str_0 = '~'
        var_0 = module_0.exchange(bytes_0, str_0)
    except BaseException:
        pass


def test_case_3():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.exchange(tuple_0, bytes_0)
    except BaseException:
        pass
