# Automatically generated by Pynguin.
import script_58 as module_0


def test_case_0():
    tuple_0 = None
    list_0 = [tuple_0, tuple_0]
    var_0 = module_0.common(list_0, list_0)
    assert var_0 == [None]


def test_case_1():
    str_0 = 'BX[9>Wz\x0b'
    list_0 = [str_0, str_0, str_0, str_0]
    list_1 = [list_0, list_0, str_0]
    var_0 = module_0.common(list_0, list_1)
    assert var_0 == ['BX[9>Wz\x0b']
    var_1 = module_0.common(list_0, list_0)
    assert var_1 == ['BX[9>Wz\x0b']
    var_2 = module_0.common(list_0, list_1)
    assert var_2 == ['BX[9>Wz\x0b']
