# Automatically generated by Pynguin.
import script_162 as module_0


def test_case_0():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.string_to_md5(set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        int_0 = -2266
        int_1 = None
        var_0 = module_0.string_to_md5(int_1)
        set_0 = None
        var_1 = module_0.string_to_md5(set_0)
        var_2 = module_0.string_to_md5(int_0)
    except BaseException:
        pass
