# Automatically generated by Pynguin.
import script_132 as module_0


def test_case_0():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.is_nested(set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        set_0 = set()
        var_0 = module_0.is_nested(set_0)
        assert var_0 is False
        list_0 = None
        str_0 = '%['
        var_1 = module_0.is_nested(str_0)
        assert var_1 is False
        var_2 = module_0.is_nested(set_0)
        assert var_2 is False
        var_3 = module_0.is_nested(set_0)
        assert var_3 is False
        var_4 = module_0.is_nested(set_0)
        assert var_4 is False
        str_1 = '['
        var_5 = module_0.is_nested(str_1)
        assert var_5 is False
        var_6 = module_0.is_nested(list_0)
    except BaseException:
        pass
