# Automatically generated by Pynguin.
import q1 as module_0


def test_case_0():
    try:
        list_0 = []
        var_0 = module_0.search(list_0, list_0)
        bool_0 = False
        str_0 = 'I~?iudiwpm:'
        var_1 = module_0.search(bool_0, str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.search(tuple_0, bytes_0)
    except BaseException:
        pass


def test_case_2():
    try:
        str_0 = 'Qn\x0bh\x0b?~?R'
        str_1 = "Ma^[(h@Ifm'O"
        var_0 = module_0.search(str_0, str_1)
        assert var_0 == 1
        bytes_0 = (
            b'_j\xb3\x8c\xe9x\xc1\x89\xcd\xaa\xd37\xc3?\xae\xc1\x98\xdf\xc9')
        str_2 = "9+e7)#p,'jl"
        var_1 = module_0.search(bytes_0, str_2)
    except BaseException:
        pass
