# Automatically generated by Pynguin.
import script_49 as module_0


def test_case_0():
    int_0 = 4235
    int_1 = -726
    var_0 = module_0.modp(int_0, int_1)
    assert var_0 == -364
    int_2 = -1470
    var_1 = module_0.modp(int_2, int_2)
    assert var_1 == 1


def test_case_1():
    int_0 = -157
    var_0 = module_0.modp(int_0, int_0)
    assert var_0 == 1
