# Automatically generated by Pynguin.
import script_19 as module_0


def test_case_0():
    try:
        str_0 = "QKdjS@-wx'"
        str_1 = module_0.sort_numbers(str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = ' zj\x0codgn3\r;;y:+;t/tt'
        str_1 = module_0.sort_numbers(str_0)
    except BaseException:
        pass
