# Automatically generated by Pynguin.

import script_19 as module_0

def test_case_1():
    str_0 = ""
    str_1 = module_0.sort_numbers(str_0)
    assert str_1 == ""
    str_2 = 'gJ+a!HE(\t"[_.#y!w'
    module_0.sort_numbers(str_2)
