# Automatically generated by Pynguin.
import script_31 as module_0


def test_case_0():
    int_0 = 246
    var_0 = module_0.is_prime(int_0)
    assert var_0 is False


def test_case_1():
    int_0 = 2899
    var_0 = module_0.is_prime(int_0)
    assert var_0 is False
