# Automatically generated by Pynguin.

import script_98 as module_0


def test_case_1():
    bytes_0 = b""
    var_0 = module_0.count_upper(bytes_0)
    assert var_0 == 0
    



def test_case_3():
    str_0 = ":$31A"
    var_0 = module_0.count_upper(str_0)
    assert var_0 == 1
    



def test_case_4():
    str_0 = "\rQl"
    var_0 = module_0.count_upper(str_0)
    assert var_0 == 0
    list_0 = []
    var_1 = module_0.count_upper(list_0)
    assert var_1 == 0
    var_2 = module_0.count_upper(list_0)
    assert var_2 == 0
    