# Automatically generated by Pynguin.
import script_65 as module_0


def test_case_0():
    try:
        int_0 = 2536
        set_0 = set()
        tuple_0 = None
        var_0 = module_0.circular_shift(tuple_0, int_0)
        assert var_0 == 'enoN'
        var_1 = module_0.circular_shift(int_0, set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = True
        float_0 = 1205.170231
        var_0 = module_0.circular_shift(bool_0, float_0)
        assert var_0 == 'eurT'
        str_0 = '<\tjukmQ3m GQ\\'
        var_1 = module_0.circular_shift(str_0, bool_0)
        assert var_1 == '\\<\tjukmQ3m GQ'
        tuple_0 = None
        str_1 = '5DK5'
        var_2 = module_0.circular_shift(tuple_0, str_1)
    except BaseException:
        pass


def test_case_2():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.circular_shift(tuple_0, bytes_0)
    except BaseException:
        pass
