# Automatically generated by Pynguin.
import script_24 as module_0


def test_case_0():
    int_0 = -1188
    int_1 = module_0.largest_divisor(int_0)
    assert int_1 is None
    assert module_0.METADATA == {'author': 'jt', 'dataset': 'test'}
