# Automatically generated by Pynguin.
import script_24 as module_0


def test_case_0():
    try:
        int_0 = 4355
        int_1 = module_0.largest_divisor(int_0)
        assert int_1 == 871

        int_2 = None
        int_3 = module_0.largest_divisor(int_2)
    except BaseException:
        pass
