# Automatically generated by Pynguin.
import script_85 as module_0


def test_case_0():
    try:
        dict_0 = {}
        list_0 = [dict_0, dict_0]
        var_0 = module_0.add(list_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.add(bytes_0)
        assert var_0 == 370
    except BaseException:
        pass
