# Automatically generated by Pynguin.
import pytest
import script_55 as module_0



def test_case_0():
    bool_0 = False
    var_0 = module_0.fib(bool_0)
    assert var_0 == 0
    var_1 = module_0.fib(var_0)
    assert var_1 == 0
    var_2 = module_0.fib(var_0)
    assert var_2 == 0
    



def test_case_2():
    bool_0 = True
    var_0 = module_0.fib(bool_0)
    assert var_0 == 1
