# Automatically generated by Pynguin.
import script_64 as module_0


def test_case_0():
    try:
        str_0 = 'cTnw!KGCec\\1^)\x0bgGK '
        var_0 = module_0.vowels_count(str_0)
        assert var_0 == 1
        str_1 = 'D`>tsHSZ7$S?6Cey'
        var_1 = module_0.vowels_count(str_1)
        assert var_1 == 2
        list_0 = None
        var_2 = module_0.vowels_count(list_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = "k|'Anm{_\\jkue5E,gUx"
        var_0 = module_0.vowels_count(str_0)
        assert var_0 == 5
        str_1 = '#G?{BYB\n,\\i+~UH_e'
        list_0 = [str_1]
        var_1 = module_0.vowels_count(list_0)
        assert var_1 == 0
        str_2 = 'Y'
        var_2 = module_0.vowels_count(str_2)
        assert var_2 == 1
        bytes_0 = b'\x7f&\xdf4'
        var_3 = module_0.vowels_count(bytes_0)
    except BaseException:
        pass
