# Automatically generated by Pynguin.
import script_8 as module_0


def test_case_0():
    int_0 = 2432
    int_1 = -3246
    list_0 = [int_0, int_0, int_1]
    tuple_0 = module_0.sum_product(list_0)
    assert tuple_0 == (1618, -19198869504)

    tuple_1 = module_0.sum_product(list_0)
    assert tuple_1 == (1618, -19198869504)


def test_case_1():
    list_0 = []
    tuple_0 = module_0.sum_product(list_0)
    assert tuple_0 == (0, 1)

