# Automatically generated by Pynguin.
import script_120 as module_0


def test_case_0():
    try:
        list_0 = []
        bool_0 = False
        var_0 = module_0.maximum(list_0, bool_0)
        complex_0 = None
        var_1 = module_0.maximum(bool_0, complex_0)
    except BaseException:
        pass


def test_case_1():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.maximum(tuple_0, bytes_0)
    except BaseException:
        pass
