# Automatically generated by Pynguin.
import script_153 as module_0


def test_case_0():
    try:
        bytes_0 = b"G'7\xf5\xc3V\x1a\x17a\x18"
        str_0 = '~'
        var_0 = module_0.Strongest_Extension(bytes_0, str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.Strongest_Extension(tuple_0, bytes_0)
    except BaseException:
        pass


def test_case_2():
    try:
        str_0 = '-IIzs:oWP,0xmQ#d*'
        str_1 = "w',w_UM+Z\x0bv\nH\x0cW^"
        var_0 = module_0.Strongest_Extension(str_0, str_1)
        assert var_0 == '-IIzs:oWP,0xmQ#d*.U'
        list_0 = [var_0, str_0, str_1, str_1]
        str_2 = ',yn\t^o'
        var_1 = module_0.Strongest_Extension(list_0, str_2)
    except BaseException:
        pass


def test_case_3():
    try:
        str_0 = '`:S<nW$S)VNJsn'
        set_0 = {str_0}
        list_0 = [str_0, set_0, set_0, str_0]
        var_0 = module_0.Strongest_Extension(set_0, list_0)
    except BaseException:
        pass
