# Automatically generated by Pynguin.

import script_125 as module_0



def test_case_0():
    str_0 = "Z"
    var_0 = module_0.split_words(str_0)
    assert var_0 == 0
    

def test_case_2():
    str_0 = "\rQl"
    var_0 = module_0.split_words(str_0)
    assert var_0 == 1
    

def test_case_3():
    set_0 = set()
    var_0 = module_0.split_words(set_0)
    assert var_0 == 0
    str_0 = "&go3T68iuZ%ZEYW3JC"
    var_1 = module_0.split_words(str_0)
    assert var_1 == 0
    var_2 = module_0.split_words(set_0)
    assert var_2 == 0
   



def test_case_5():
    str_0 = "s[4?T\n "
    var_0 = module_0.split_words(str_0)
    set_0 = set()
    var_1 = module_0.split_words(set_0)
    assert var_1 == 0
    str_1 = "\rQl"
    var_2 = module_0.split_words(str_1)
    assert var_2 == 1
   