# Automatically generated by Pynguin.
import script_74 as module_0


def test_case_0():
    str_0 = "n"
    var_0 = module_0.total_match(str_0, str_0)
    assert var_0 == "n"
    var_1 = module_0.total_match(str_0, str_0)
    assert var_1 == "n"
