# Automatically generated by Pynguin.
import script_74 as module_0


def test_case_0():
    try:
        str_0 = '~bLHnePP'
        list_0 = [str_0, str_0, str_0]
        bytes_0 = b'\x1c\xe3ip\x0b\x10B\xa7P\x03\xb4\xde\xad\x86\xc4'
        var_0 = module_0.total_match(list_0, bytes_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = '`:S<nW$S)VNJsn'
        set_0 = {str_0}
        list_0 = [str_0, set_0, set_0, str_0]
        var_0 = module_0.total_match(set_0, list_0)
        assert var_0 == {'`:S<nW$S)VNJsn'}
        str_1 = 'PgB7L)60{*JeA3uT'
        var_1 = module_0.total_match(str_1, set_0)
        assert var_1 == {'`:S<nW$S)VNJsn'}
    except BaseException:
        pass


def test_case_2():
    try:
        bytes_0 = b"G'7\xf5\xc3V\x1a\x17a\x18"
        str_0 = '~'
        var_0 = module_0.total_match(bytes_0, str_0)
    except BaseException:
        pass


def test_case_3():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.total_match(tuple_0, bytes_0)
    except BaseException:
        pass
