# Automatically generated by Pynguin.

import script_141 as module_0


def test_case_0():
    str_0 = "y"
    var_0 = module_0.file_name_check(str_0)
    assert var_0 == "No"




def test_case_2():
    str_0 = "lE$})P.W(V"
    var_0 = module_0.file_name_check(str_0)
    assert var_0 == "No"


def test_case_3():
    str_0 = "J(P.dll"
    var_0 = module_0.file_name_check(str_0)
    assert var_0 == "Yes"


def test_case_4():
    str_0 = "(P.dll"
    var_0 = module_0.file_name_check(str_0)
    assert var_0 == "No"


def test_case_5():
    str_0 = ".dll"
    var_0 = module_0.file_name_check(str_0)
    assert var_0 == "No"
    var_1 = module_0.file_name_check(str_0)
    assert var_1 == "No"
    var_2 = module_0.file_name_check(var_0)
    assert var_2 == "No"
  


def test_case_6():
    str_0 = "J60).dll"
    var_0 = module_0.file_name_check(str_0)
    assert var_0 == "Yes"


def test_case_7():
    str_0 = "B44J60).dll"
    var_0 = module_0.file_name_check(str_0)
    assert var_0 == "No"
    var_1 = module_0.file_name_check(str_0)
    assert var_1 == "No"
    var_2 = module_0.file_name_check(var_0)
    assert var_2 == "No"
    var_3 = module_0.file_name_check(var_2)
    assert var_3 == "No"
