# Automatically generated by Pynguin.
import script_129 as module_0


def test_case_0():
    set_0 = set()
    tuple_0 = ()
    bool_0 = True
    var_0 = module_0.minPath(tuple_0, bool_0)
    assert var_0 == [1]
    int_0 = -875
    var_1 = module_0.minPath(set_0, int_0)
    assert var_1 == []
