# Automatically generated by Pynguin.
import script_89 as module_0


def test_case_0():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.encrypt(set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = "t)7N%R'^Y,uYCaO|4#"
        var_0 = module_0.encrypt(str_0)
        assert var_0 == "x)7N%R'^Y,yYCeO|4#"
        bool_0 = False
        set_0 = {bool_0}
        var_1 = module_0.encrypt(set_0)
    except BaseException:
        pass
