# Automatically generated by Pynguin.
import script_67 as module_0


def test_case_0():
    try:
        str_0 = "k|'Anm{_\\jkue5E,gUx"
        var_0 = module_0.fruit_distribution(str_0, str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = '7'
        set_0 = set()
        float_0 = -1428.06
        bytes_0 = b'\x89\xe3q\xca*\xe4\x8c\xee%\x0ff1&(\xb1\xa9\x84'
        tuple_0 = set_0, float_0, bytes_0
        tuple_1 = tuple_0,
        var_0 = module_0.fruit_distribution(str_0, tuple_1)
    except BaseException:
        pass
