# Automatically generated by Pynguin.
import script_152 as module_0



def test_case_1():
    bool_0 = True
    set_0 = {bool_0}
    var_0 = module_0.compare(set_0, set_0)
    var_1 = module_0.compare(var_0, var_0)
