# Automatically generated by Pynguin.
import script_155 as module_0


def test_case_0():
    try:
        int_0 = -2191
        var_0 = module_0.even_odd_count(int_0)
        assert var_0 == (1, 3)
        float_0 = None
        var_1 = module_0.even_odd_count(float_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.even_odd_count(set_0)
    except BaseException:
        pass
