# Automatically generated by Pynguin.
import script_71 as module_0


def test_case_0():
    try:
        float_0 = -533.814
        tuple_0 = ()
        str_0 = 'x4d/TI~ET:$eN,ow5{'
        var_0 = module_0.triangle_area(float_0, tuple_0, str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = 'Tbs'
        var_0 = module_0.triangle_area(str_0, str_0, str_0)
    except BaseException:
        pass
