# Automatically generated by Pynguin.
import script_86 as module_0


def test_case_0():
    try:
        str_0 = "t)7N%R'^Y,uYCaO|4#"
        var_0 = module_0.anti_shuffle(str_0)
        assert var_0 == "#%'),47CNORYY^atu|"
        bool_0 = False
        set_0 = {bool_0}
        var_1 = module_0.anti_shuffle(set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.anti_shuffle(set_0)
    except BaseException:
        pass
