# Automatically generated by Pynguin.
import script_145 as module_0


def test_case_0():
    bytes_0 = b"@\xa8'\xb7l\xca`"
    var_0 = module_0.order_by_points(bytes_0)
    assert var_0 == [202, 108, 64, 39, 183, 168, 96]
