# Automatically generated by Pynguin.
import script_145 as module_0


def test_case_0():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.order_by_points(set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        int_0 = 106
        list_0 = [int_0]
        var_0 = module_0.order_by_points(list_0)
        assert var_0 == [106]
        float_0 = -2161.0
        set_0 = {float_0, float_0, float_0, float_0}
        bytes_0 = b'r\n\xba\xde\xe9Z\x9d\xffoF\xa3'
        var_1 = module_0.order_by_points(bytes_0)
        assert var_1 == [10, 111, 114, 222, 70, 233, 90, 163, 255, 157, 186]
        var_2 = module_0.order_by_points(set_0)
    except BaseException:
        pass
