# Automatically generated by Pynguin.
import script_159 as module_0


def test_case_0():
    try:
        tuple_0 = ()
        list_0 = None
        str_0 = '8e"/\'2=$,u|iBS'
        float_0 = None
        tuple_1 = tuple_0, list_0, str_0, float_0
        str_1 = '&K'
        str_2 = ')2NY5>NLw\t2J8Iu~'
        var_0 = module_0.eat(tuple_1, str_1, str_2)
    except BaseException:
        pass


def test_case_1():
    try:
        float_0 = None
        bool_0 = True
        int_0 = -2903
        var_0 = module_0.eat(float_0, bool_0, int_0)
    except BaseException:
        pass


def test_case_2():
    try:
        float_0 = -533.814
        tuple_0 = ()
        str_0 = 'x4d/TI~ET:$eN,ow5{'
        var_0 = module_0.eat(float_0, tuple_0, str_0)
    except BaseException:
        pass
