# Automatically generated by Pynguin.
import script_54 as module_0


def test_case_0():
    try:
        str_0 = None
        var_0 = module_0.same_chars(str_0, str_0)
    except BaseException:
        pass
