# Automatically generated by Pynguin.
import script_69 as module_0


def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.search(set_0)
    assert var_0 == -1
