# Automatically generated by Pynguin.
import script_69 as module_0


def test_case_0():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.search(bytes_0)
        assert var_0 == -1
    except BaseException:
        pass


def test_case_1():
    try:
        bytes_0 = b'r\x9d\x01\xe7\x14\x04A7\xd5&\x8c\xf0\xba\x9b\x87'
        var_0 = module_0.search(bytes_0)
        assert var_0 == 1
        set_0 = {var_0}
        var_1 = module_0.search(set_0)
        assert var_1 == 1
        float_0 = -1837.0
        var_2 = module_0.search(float_0)
    except BaseException:
        pass
