# Automatically generated by Pynguin.
import script_50 as module_0


def test_case_0():
    str_0 = '_gqi>y%VQum;_4/'
    var_0 = module_0.encode_shift(str_0)
    assert var_0 == 'dlvnwdxupzrtdmh'



def test_case_1():
    str_0 = 'dN#.'
    var_0 = module_0.decode_shift(str_0)
    assert var_0 == 'yclw'

