# Automatically generated by Pynguin.
import script_3 as module_0


def test_case_0():
    int_0 = -2973
    int_1 = 815
    list_0 = [int_0, int_0, int_1]
    bool_0 = module_0.below_zero(list_0)
    assert bool_0 is True



def test_case_1():
    int_0 = 2432
    int_1 = -3246
    list_0 = [int_0, int_0, int_1]
    bool_0 = module_0.below_zero(list_0)
    assert bool_0 is False
    bool_1 = module_0.below_zero(list_0)
    assert bool_1 is False
