# Automatically generated by Pynguin.
import script_111 as module_0


def test_case_0():
    str_0 = "\rQl"
    var_0 = module_0.histogram(str_0)



def test_case_2():
    str_0 = '{- ,"sABwz8'
    var_0 = module_0.histogram(str_0)



def test_case_4():
    str_0 = ' ,"9sABhz8'
    var_0 = module_0.histogram(str_0)


def test_case_5():
    str_0 = ' /  d"9sA!z8'
    var_0 = module_0.histogram(str_0)