# Automatically generated by Pynguin.
import q2 as module_0


def test_case_0():
    bytes_0 = b'\x15\xd6\xc2\x7f3`t\x16\x1c\xe8\xaa\xdd\xe7\xc2\x18\xcfJ/\x06t'
    list_0 = [bytes_0, bytes_0, bytes_0]
    tuple_0 = list_0,
    var_0 = module_0.contains_unique_day(bytes_0, tuple_0)
    assert var_0 is True


def test_case_1():
    bytes_0 = b'\xe4\xc5\x96\xbb\xdbJ"'
    set_0 = set()
    var_0 = module_0.unique_month(bytes_0, set_0)
    assert var_0 is False


def test_case_2():
    str_0 = 'Vl'
    var_0 = module_0.contains_unique_day(str_0, str_0)
    assert var_0 is False


def test_case_3():
    bool_0 = True
    str_0 = 'X"D"2bO#Wur-J66A'
    int_0 = -3149
    set_0 = {str_0}
    var_0 = module_0.unique_day(int_0, set_0)
    assert var_0 is False
    list_0 = [bool_0, bool_0, str_0]
    var_1 = module_0.contains_unique_day(list_0, str_0)
    assert var_1 is False
    var_2 = module_0.unique_month(int_0, set_0)
    assert var_2 is False
