# Automatically generated by Pynguin.
import script_6 as module_0


def test_case_0():
    str_0 = 'Y'
    list_0 = module_0.parse_nested_parens(str_0)
    assert list_0 == [0]



def test_case_1():
    str_0 = "+T&>>'DIZ(tbUDKQxjC1"
    list_0 = module_0.parse_nested_parens(str_0)
    assert list_0 == [0]

    list_1 = module_0.parse_nested_parens(str_0)
    assert list_1 == [0]
    list_2 = module_0.parse_nested_parens(str_0)
    assert list_2 == [0]
    str_1 = '=gg&l34[JFYX(y'
    list_3 = module_0.parse_nested_parens(str_1)
    assert list_3 == [0]


def test_case_2():
    str_0 = 'Le\rz,sS*\x0b<;]?*3:['
    list_0 = module_0.parse_nested_parens(str_0)
    assert list_0 == [0]

    str_1 = ' >3b'
    list_1 = module_0.parse_nested_parens(str_1)
    assert list_1 == [0]
    list_2 = module_0.parse_nested_parens(str_0)
    assert list_2 == [0]
    str_2 = '*G\\fQJ\\\nS}6A/DJd,'
    list_3 = module_0.parse_nested_parens(str_2)
    assert list_3 == [0]
