# Automatically generated by Pynguin.
import script_82 as module_0


def test_case_0():
    dict_0 = {}
    list_0 = [dict_0, dict_0]
    var_0 = module_0.prime_length(list_0)
    assert var_0 is True
    tuple_0 = ()
    var_1 = module_0.prime_length(tuple_0)
    assert var_1 is False


def test_case_1():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.prime_length(set_0)
    assert var_0 is False
