# Automatically generated by Pynguin.
import script_82 as module_0


def test_case_0():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.prime_length(bytes_0)
        assert var_0 is True
    except BaseException:
        pass


def test_case_1():
    try:
        bytes_0 = b'Q\xe9\xba\xea\xce\x11\x16c'
        var_0 = module_0.prime_length(bytes_0)
        assert var_0 is False
        float_0 = 3170.2194
        dict_0 = {var_0: var_0, var_0: var_0}
        list_0 = [bytes_0, dict_0, float_0, dict_0]
        var_1 = module_0.prime_length(list_0)
        assert var_1 is False
        var_2 = module_0.prime_length(float_0)
    except BaseException:
        pass
