# Automatically generated by Pynguin.
import script_78 as module_0


def test_case_0():
    dict_0 = {}
    list_0 = [dict_0, dict_0]
    var_0 = module_0.hex_key(list_0)
    assert var_0 == 0
    tuple_0 = ()
    var_1 = module_0.hex_key(tuple_0)
    assert var_1 == 0
