# Automatically generated by Pynguin.
import script_140 as module_0


def test_case_0():
    str_0 = "c(?6 "
    var_0 = module_0.fix_spaces(str_0)
    assert var_0 == "c(?6_"



def test_case_1():
    bytes_0 = b""
    var_0 = module_0.fix_spaces(bytes_0)
    assert var_0 == ""
    



def test_case_3():
    str_0 = "t Hal\\\x0c)a$p$]-b"
    var_0 = module_0.fix_spaces(str_0)
    assert var_0 == "t_Hal\\\x0c)a$p$]-b"


def test_case_4():
    str_0 = " "
    list_0 = [str_0, str_0, str_0]
    var_0 = module_0.fix_spaces(list_0)
    assert var_0 == "-"
    var_1 = module_0.fix_spaces(var_0)
    assert var_1 == "-"
    var_2 = module_0.fix_spaces(var_0)
    assert var_2 == "-"
    var_3 = module_0.fix_spaces(str_0)
    assert var_3 == "_"
    var_4 = module_0.fix_spaces(var_0)
    assert var_4 == "-"
    var_5 = module_0.fix_spaces(var_4)
    assert var_5 == "-"
    var_6 = module_0.fix_spaces(var_4)
    assert var_6 == "-"


def test_case_5():
    str_0 = "  z5Z8P|"
    list_0 = []
    var_0 = module_0.fix_spaces(str_0)
    assert var_0 == "__z5Z8P|"
    var_1 = module_0.fix_spaces(list_0)
    assert var_1 == ""
    var_2 = module_0.fix_spaces(list_0)
    assert var_2 == ""
    var_3 = module_0.fix_spaces(var_0)
    assert var_3 == "__z5Z8P|"
    var_4 = module_0.fix_spaces(str_0)
    assert var_4 == "__z5Z8P|"
    str_1 = "c/(?z6 "
    var_5 = module_0.fix_spaces(str_1)
    assert var_5 == "c/(?z6_"
    list_1 = [str_1, str_0, var_0, str_0, str_0]
    var_6 = module_0.fix_spaces(list_1)
    assert var_6 == "c/(?z6   z5Z8P|__z5Z8P|  z5Z8P|  z5Z8P|"
    var_7 = module_0.fix_spaces(list_1)
    assert var_7 == "c/(?z6   z5Z8P|__z5Z8P|  z5Z8P|  z5Z8P|"
    var_8 = module_0.fix_spaces(var_4)
    assert var_8 == "__z5Z8P|"
    var_9 = module_0.fix_spaces(var_6)
    assert var_9 == "c/(?z6-z5Z8P|__z5Z8P|__z5Z8P|__z5Z8P|"
    var_10 = module_0.fix_spaces(var_9)
    assert var_10 == "c/(?z6-z5Z8P|__z5Z8P|__z5Z8P|__z5Z8P|"