# Automatically generated by Pynguin.
import script_17 as module_0


def test_case_0():
    try:
        str_0 = 'Y'
        list_0 = module_0.parse_music(str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = ''
        list_0 = module_0.parse_music(str_0)
        assert list_0 == []
        assert module_0.METADATA == {'author': 'jt', 'dataset': 'test'}
        str_1 = None
        list_1 = module_0.parse_music(str_1)
    except BaseException:
        pass
