from script_107_cp_normal import even_odd_palindrome

def test_even_odd_palindrome():
    assert even_odd_palindrome(3) == (0, 1)
    assert even_odd_palindrome(4) == (1, 0)
    assert even_odd_palindrome(5) == (1, 1)
    assert even_odd_palindrome(6) == (2, 1)
    assert even_odd_palindrome(7) == (2, 2)
    assert even_odd_palindrome(8) == (3, 2)
    assert even_odd_palindrome(9) == (3, 3)
    assert even_odd_palindrome(10) == (4, 3)
    assert even_odd_palindrome(11) == (4, 4)
    assert even_odd_palindrome(12) == (5, 4)
    assert even_odd_palindrome(13) == (5, 5)
    assert even_odd_palindrome(14) == (6, 5)
    assert even_odd_palindrome(15) == (6, 6)
    assert even_odd_palindrome(16) == (7, 6)
    assert even_odd_palindrome(17) == (7, 7)
    assert even_odd_palindrome(18) == (8, 7)
    assert even_odd_palindrome(19) == (8, 8)
    assert even_odd_palindrome(20) == (9, 8)
    assert even_odd_palindrome(21) == (9, 9)
    assert even_odd_palindrome(22) == (10, 9)
    assert even_odd_palindrome(23) == (10, 10)
    assert even_odd_palindrome(24) == (11, 10)
    assert even_odd_palindrome(25) == (11, 11)
    assert even_odd_palindrome(26) == (12, 11)