# Automatically generated by Pynguin.
import script_136 as module_0


def test_case_0():
    try:
        bytes_0 = b'uk+\xc2W8\xe2K\x9a(\xca\xcb\xa3\xf3'
        var_0 = module_0.largest_smallest_integers(bytes_0)
        assert var_0 == (None, 40)
        bytes_1 = b'\xc6\xd7a%\xd2\xae>\x08\x92\xf2\xb3\x1c0\x04pPk&i'
        set_0 = {bytes_1, bytes_1}
        var_1 = module_0.largest_smallest_integers(set_0)
    except BaseException:
        pass


def test_case_1():
    try:
        int_0 = -1527
        list_0 = [int_0]
        var_0 = module_0.largest_smallest_integers(list_0)
        assert var_0 == (-1527, None)
        str_0 = '=U'
        var_1 = module_0.largest_smallest_integers(str_0)
    except BaseException:
        pass
