# Automatically generated by Pynguin.
import script_136 as module_0


def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.largest_smallest_integers(set_0)
    assert var_0 == (None, None)
