# Automatically generated by Pynguin.
import script_23 as module_0


def test_case_0():
    str_0 = 'dN#.'
    int_0 = module_0.strlen(str_0)
    assert module_0.METADATA == {'author': 'jt', 'dataset': 'test'}
