# Automatically generated by Pynguin.
import script_80 as module_0


def test_case_0():
    try:
        bytes_0 = b'Q\xe9\xba\xea\xce\x11\x16c'
        var_0 = module_0.is_happy(bytes_0)
        assert var_0 is True
        float_0 = 3170.2194
        var_1 = module_0.is_happy(float_0)
    except BaseException:
        pass


def test_case_1():
    try:
        int_0 = 2516
        list_0 = [int_0, int_0, int_0, int_0]
        var_0 = module_0.is_happy(list_0)
        assert var_0 is False
        dict_0 = {int_0: int_0, int_0: int_0, int_0: int_0, int_0: int_0}
        bytes_0 = b'\\\x1b\x17\x01\xf1Nq\\\xc2E'
        var_1 = module_0.is_happy(bytes_0)
        assert var_1 is True
        tuple_0 = dict_0,
        var_2 = module_0.is_happy(tuple_0)
        assert var_2 is False
        var_3 = module_0.is_happy(int_0)
    except BaseException:
        pass


def test_case_2():
    try:
        bytes_0 = b'Q\xe9\xba\xea\xce\x11\x16c'
        var_0 = module_0.is_happy(bytes_0)
        assert var_0 is True
        float_0 = 3170.2194
        dict_0 = {var_0: var_0, var_0: var_0}
        list_0 = [bytes_0, dict_0, float_0, dict_0]
        var_1 = module_0.is_happy(list_0)
        assert var_1 is False
        var_2 = module_0.is_happy(float_0)
    except BaseException:
        pass
