# Automatically generated by Pynguin.
import script_112 as module_0


def test_case_0():
    str_0 = "n"
    var_0 = module_0.reverse_delete(str_0, str_0)
    var_1 = module_0.reverse_delete(str_0, str_0)
