# Automatically generated by Pynguin.
import script_151 as module_0


def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.double_the_difference(set_0)


def test_case_1():
    bytes_0 = b"@\xa8'\xb7l\xca`"
    var_0 = module_0.double_the_difference(bytes_0)
    assert var_0 == 35010
