# Automatically generated by Pynguin.
import script_151 as module_0


def test_case_0():
    try:
        float_0 = 998.744
        list_0 = []
        var_0 = module_0.double_the_difference(list_0)
        var_1 = module_0.double_the_difference(list_0)
        list_1 = [float_0, float_0, float_0]
        var_2 = module_0.double_the_difference(list_1)
        assert var_2 == 0
        set_0 = {var_2, var_0, float_0, var_0}
        var_3 = module_0.double_the_difference(set_0)
        assert var_3 == 0
        str_0 = '$Q[o0>F2>K5 F]U'
        var_4 = module_0.double_the_difference(str_0)
    except BaseException:
        pass
