# Automatically generated by Pynguin.
import script_73 as module_0


def test_case_0():
    try:
        bytes_0 = b"@\xa8'\xb7l\xca`"
        var_0 = module_0.smallest_change(bytes_0)
        assert var_0 == 3
    except BaseException:
        pass
