# Automatically generated by Pynguin.
import pytest
import script_83 as module_0


def test_case_0():
    try:
        bool_0 = True
        bool_1 = False
        var_0 = module_0.starts_one_ends(bool_1)
        assert var_0 == pytest.approx(0.18, abs=0.01, rel=0.01)
        var_1 = module_0.starts_one_ends(bool_0)
        assert var_1 == 1
        bool_2 = None
        var_2 = module_0.starts_one_ends(bool_2)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.starts_one_ends(set_0)
    except BaseException:
        pass
