# Automatically generated by Pynguin.
import script_88 as module_0


def test_case_0():
    try:
        tuple_0 = ()
        var_0 = module_0.sort_array(tuple_0)
        assert var_0 == []
        str_0 = 'ikns;woen\\+6\n)X?'
        var_1 = module_0.sort_array(str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = False
        set_0 = {bool_0, bool_0, bool_0, bool_0}
        var_0 = module_0.sort_array(set_0)
    except BaseException:
        pass
