# Automatically generated by Pynguin.
import q5 as module_0


def test_case_0():
    try:
        int_0 = 2536
        tuple_0 = None
        var_0 = module_0.top_k(tuple_0, int_0)
    except BaseException:
        pass


def test_case_1():
    try:
        set_0 = set()
        int_0 = -875
        var_0 = module_0.top_k(set_0, int_0)
    except BaseException:
        pass


def test_case_2():
    try:
        tuple_0 = ()
        bytes_0 = None
        var_0 = module_0.top_k(tuple_0, bytes_0)
    except BaseException:
        pass
