# Automatically generated by Pynguin.
import script_128 as module_0


def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    var_0 = module_0.prod_signs(set_0)
    assert var_0 == 0
