# Automatically generated by Pynguin.
import script_128 as module_0


def test_case_0():
    try:
        int_0 = -2266
        int_1 = None
        var_0 = module_0.prod_signs(int_1)
        assert var_0 is None
        set_0 = None
        var_1 = module_0.prod_signs(set_0)
        assert var_1 is None
        var_2 = module_0.prod_signs(int_0)
    except BaseException:
        pass


def test_case_1():
    try:
        dict_0 = {}
        list_0 = [dict_0, dict_0]
        var_0 = module_0.prod_signs(list_0)
    except BaseException:
        pass
