# Automatically generated by Pynguin.
import script_138 as module_0


def test_case_0():
    float_0 = 1957.138153
    var_0 = module_0.is_equal_to_sum_even(float_0)
    assert var_0 is False
    int_0 = 246
    var_1 = module_0.is_equal_to_sum_even(int_0)
    assert var_1 is True
