# Automatically generated by Pynguin.
import script_21 as module_0


def test_case_0():
    try:
        list_0 = []
        list_1 = module_0.rescale_to_unit(list_0)
    except BaseException:
        pass
