# Automatically generated by Pynguin.
import script_21 as module_0


def test_case_0():
    float_0 = -1429.370969
    float_1 = -605.603871
    float_2 = -316.6
    list_0 = [float_0, float_1, float_0, float_2]
    list_1 = module_0.rescale_to_unit(list_0)

