# Automatically generated by Pynguin.
# Automatically generated by Pynguin.
import script_95 as module_0



def test_case_0():
    str_0 = "z# !9-T"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.check_dict_case(dict_0)
    assert var_0 is False
    dict_1 = {}
    var_1 = module_0.check_dict_case(dict_1)
    assert var_1 is False
    var_2 = module_0.check_dict_case(dict_1)
    assert var_2 is False
    

def test_case_1():
    float_0 = 912.8
    dict_0 = {
        float_0: float_0,
        float_0: float_0,
        float_0: float_0,
        float_0: float_0,
        float_0: float_0,
    }
    var_0 = module_0.check_dict_case(dict_0)
    assert var_0 is False




def test_case_3():
    str_0 = "mixed"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.check_dict_case(dict_0)
    assert var_0 is True


def test_case_4():
    str_0 = ")ZxPm1nX!z9#S-"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.check_dict_case(dict_0)
    assert var_0 is False


def test_case_5():
    str_0 = "-6\t!A"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.check_dict_case(dict_0)
    assert var_0 is True


def test_case_6():
    str_0 = "start"
    str_1 = "wa-}\n"
    dict_0 = {str_0: str_0, str_1: str_1}
    var_0 = module_0.check_dict_case(dict_0)
    assert var_0 is True


def test_case_7():
    str_0 = "start"
    str_1 = ",{"
    dict_0 = {str_0: str_0, str_1: str_1}
    var_0 = module_0.check_dict_case(dict_0)
    assert var_0 is False


def test_case_8():
    str_0 = "L"
    str_1 = ";wa-x\n"
    dict_0 = {str_0: str_1, str_0: str_0, str_1: str_1}
    var_0 = module_0.check_dict_case(dict_0)
    assert var_0 is False



def test_case_9():
    str_0 = "BEI"
    str_1 = "X%}\n"
    dict_0 = {str_0: str_0, str_1: str_0, str_0: str_1, str_1: str_1}
    var_0 = module_0.check_dict_case(dict_0)
    assert var_0 is True
    