# Automatically generated by Pynguin.
import script_27 as module_0


def test_case_0():
    str_0 = "QKdjS@-wx'"
    str_1 = module_0.flip_case(str_0)
    assert module_0.METADATA == {'author': 'jt', 'dataset': 'test'}
