# Automatically generated by Pynguin.
import script_20 as module_0


def test_case_0():
    try:
        float_0 = -15.8
        float_1 = -3620.76
        list_0 = [float_0, float_1, float_1, float_1]
        tuple_0 = module_0.find_closest_elements(list_0)
        assert len(tuple_0) == 2

        list_1 = None
        tuple_1 = module_0.find_closest_elements(list_1)
    except BaseException:
        pass
