# Automatically generated by Pynguin.
import pytest
import script_35 as module_0


def test_case_0():
    try:
        str_0 = "F.Nu,2A2?,0XAgP4'&5"
        list_0 = [str_0, str_0]
        var_0 = module_0.max_element(list_0)
        bytes_0 = (
            b'\xd1\x10s*\xe3\x08\xf5\x82@\x96hK\x9a\xd3\xe0\xa5\xf3\xf7\x87Z')
        tuple_0 = ()
        float_0 = 490.0
        tuple_1 = bytes_0, tuple_0, float_0
        int_0 = -1863
        list_1 = [int_0, float_0]
        var_1 = module_0.max_element(list_1)
        assert var_1 == pytest.approx(490.0, abs=0.01, rel=0.01)
        tuple_2 = tuple_1, int_0
        var_2 = module_0.max_element(list_1)
        assert var_2 == pytest.approx(490.0, abs=0.01, rel=0.01)
        list_2 = [tuple_2, float_0, float_0]
        var_3 = module_0.max_element(list_2)
    except BaseException:
        pass
