# Automatically generated by Pynguin.
import script_35 as module_0


def test_case_0():
    float_0 = 890.6
    list_0 = [float_0, float_0, float_0, float_0]
    var_0 = module_0.max_element(list_0)


   
def test_case_1():
    bytes_0 = b"]\xa4\xf4\xf3\x0c[\xb2\x13"
    var_0 = module_0.max_element(bytes_0)
    assert var_0 == 244

