# Automatically generated by Pynguin.
import script_33 as module_0


def test_case_0():
    float_0 = 890.6
    list_0 = [float_0, float_0, float_0, float_0]
    var_0 = module_0.sort_third(list_0)
    assert len(var_0) == 4

