# Automatically generated by Pynguin.
import script_123 as module_0


def test_case_0():
    float_0 = 1887.005859
    var_0 = module_0.get_odd_collatz(float_0)


def test_case_1():
    bool_0 = True
    var_0 = module_0.get_odd_collatz(bool_0)


def test_case_2():
    float_0 = 201.86
    bool_0 = False
    var_0 = module_0.get_odd_collatz(bool_0)
    var_1 = module_0.get_odd_collatz(float_0)
    var_2 = module_0.get_odd_collatz(float_0)
