# Automatically generated by Pynguin.
import script_22 as module_0


def test_case_0():
    bytes_0 = b'thq\x14\x99\x99\x01>\xe1\x8cG\x9e\xa0\x8e\xd1'
    list_0 = [bytes_0, bytes_0, bytes_0]
    list_1 = module_0.filter_integers(list_0)



def test_case_1():
    list_0 = []
    list_1 = module_0.filter_integers(list_0)

    bool_0 = True
    list_2 = [bool_0]
    list_3 = module_0.filter_integers(list_2)
