# Automatically generated by Pynguin.
import script_76 as module_0



def test_case_0():
    int_0 = 63
    var_0 = module_0.is_simple_power(int_0, int_0)
    assert var_0 is True
    var_1 = module_0.is_simple_power(var_0, var_0)
    assert var_1 is True
    var_2 = module_0.is_simple_power(var_0, var_1)
    assert var_2 is True
    var_3 = module_0.is_simple_power(var_2, var_2)
    assert var_3 is True



def test_case_2():
    int_0 = 63
    var_0 = module_0.is_simple_power(int_0, int_0)
    assert var_0 is True


def test_case_3():
    bool_0 = False
    var_0 = module_0.is_simple_power(bool_0, bool_0)
    assert var_0 is False
    bytes_0 = b"{\xe1~E\x06J:_"
    var_1 = module_0.is_simple_power(bool_0, bytes_0)
    assert var_1 is False
    

def test_case_4():
    int_0 = 3252
    int_1 = -1036
    var_0 = module_0.is_simple_power(int_0, int_1)
    assert var_0 is False
    var_1 = module_0.is_simple_power(int_0, int_0)
    assert var_1 is True
    var_2 = module_0.is_simple_power(int_1, var_0)
    assert var_2 is False
